app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'your_secret_key'

    from .routes import main
    app.register_blueprint(main)

    return app

app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session
# from .data.questions import QUESTIONS
import json
import random

main = Blueprint('main', __name__)
quiz_started = False

# questions_path = r".\\data\\teamcenter-all-questions.json"
# questions_path = r".\\data\\devops-quiz.json"
questions_path = r".\\data\\devopspi_quiz_s1_fixed_50-50.json"

with open(questions_path, 'r', encoding='utf8') as file:
        QUESTIONS_ORIGINAL = json.load(file)

def shuffle_questions(questions_path, original_questions):
    for level in original_questions:
        for category_dict in original_questions[level]:
            for category, questions in category_dict.items():
                random.shuffle(questions)

    # Stocker le résultat dans une variable
    QUESTIONS = original_questions
    return QUESTIONS

QUESTIONS = shuffle_questions(questions_path, QUESTIONS_ORIGINAL)
# QUESTIONS = QUESTIONS_ORIGINAL

# Liste des thèmes disponibles
THEMES = list(QUESTIONS.keys())

def get_questions(theme):
    """Retourne toutes les questions associées à un thème donné."""
    questions = []
    if theme in QUESTIONS:
        # Parcourir chaque catégorie et accumuler les questions
        for category in QUESTIONS[theme]:
            for question_list in category.values():
                questions.extend(question_list)  # Ajouter les questions du niveau 3
    # Mélanger les questions et les stocker dans la session
    # random.shuffle(questions)
    return questions


@main.route('/')
def index():
    return render_template('index.html', themes=THEMES)


@main.route('/quiz', methods=['POST'])
def start_quiz():
    selected_theme = request.form.get('theme')
    if selected_theme not in THEMES:
        return redirect(url_for('main.index'))  # Redirige si le thème est invalide

    # Initialiser la session pour le quiz
    session['score'] = 0
    session['current_question'] = 0  # Position de la question courante
    session['selected_theme'] = selected_theme  # Garder le thème pour les résultats
    
    # questions = get_questions(selected_theme)
    session['questions'] = 'test'

    session['wrong_answers'] = []
    quiz_started = True
    return redirect(url_for('main.quiz', theme=selected_theme, question_index=0))


@main.route('/quiz/<theme>/<int:question_index>', methods=['GET', 'POST'])
def quiz(theme, question_index):
    questions = get_questions(theme)
    test = session.get('questions')
    total_questions = len(questions)


    # Si question_index est trop grand (fin du quiz), rediriger vers les résultats
    if question_index >= len(questions):
        return redirect(url_for('main.result', theme=theme))

    question = questions[question_index]

    user_answer = None
    is_correct = None
    
    if request.method == 'POST':
        # Récupérer la réponse de l'utilisateur
        # user_answer = request.form.getlist('answer')
        user_answer = request.form.get('answer')

        # Comparer la réponse de l'utilisateur avec la bonne réponse
        correct = question['correct']
        # if len(correct)>1:
        # is_correct = set(user_answer) == set(correct)
        is_correct = user_answer == correct
        # else:
        #     is_correct = ??

        # Initialiser les mauvaises réponses dans la session si non existantes
        if 'wrong_answers' not in session:
            session['wrong_answers'] = []

        # Si la réponse est correcte, augmenter le score
        if is_correct:
            session['score'] += 1
        else:
            # Stocker les mauvaises réponses sous forme de dictionnaire avec contexte
            session['wrong_answers'].append({
                'question': question['question'],
                'user_answer': user_answer,
                'correct_answer': correct
            })
            session.modified = True  # Assurer la mise à jour

        print("Après modification - wrong_answers :", session.get('wrong_answers'))
        
    score = session.get('score', 0)
    if question_index==0:
        success_rate=0
    else:
        success_rate = round(100*score/(question_index), 2)

    return render_template(
        'quiz.html', 
        theme=theme, 
        question=question, 
        question_index=question_index,
        user_answer=user_answer,
        is_correct=is_correct,
        questions=questions,
        total_questions=total_questions,
        score=score,
        success_rate=success_rate
    )


@main.route('/quiz/<theme>/result', methods=['GET'])
def result(theme):
    # questions = QUESTIONS.get(theme, [])
    questions = get_questions(theme)
    score = session.get('score', 0)
    total_questions = len(questions)  # Calculer le nombre total de questions
    success_rate = round(100*score/(total_questions), 1)
    correct_answers = []

    wrong_answers = session.get('wrong_answers',[])
    print("Données dans session['wrong_answers'] :", wrong_answers)  # Ajout de log

    # Pour chaque question, on affiche la bonne réponse
    for question in questions:
        correct_answers.append({
            'question': question['question'],
            'correct_answer': question['correct']
        })

    return render_template(
        'result.html',
        score=score,
        correct_answers=correct_answers,
        questions=questions,
        total_questions=total_questions,
        theme=theme,
        success_rate=success_rate,
        wrong_answers=wrong_answers)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>QCM App</title>
</head>
<body>
    <header>
        <div class="navbar">
            <div class="logo">QCM Test Training</div>
            <div class="menu">
                <ul>
                    <li><a href="{{ url_for('main.index') }}">Accueil</a></li>
                    <li><a href="{{ url_for('main.index') }}">Thèmes</a></li>
                </ul>
            </div>
        </div>
    </header>
        
    <div class="container">
        <h1 style="color: rgb(4, 152, 163);">Linux command line training </h1>
        {% block content %}
        <!-- Contenu spécifique à chaque page -->
        {% endblock %}
    </div>

    <footer>
        <div class="footer">
            <p>&copy; Jodré DIANGIENDA MAYOUNGA - Application QCM - 2024 </p>
        </div>
    </footer>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}Quiz - QCM{% endblock %}

{% block content %}
    <div class="selection-container">        
        <p>Sélectionnez un thème pour commencer :</p>        
        <!-- Formulaire pour choisir un thème -->
         <div class="form-container">
             <form action="{{ url_for('main.start_quiz') }}" method="POST">
                 <label for="theme">Thèmes :</label>
                 <select name="theme" id="theme" required>
                     <option value="" disabled selected>-- Choisissez un thème --</option>                     
                     {% for theme in themes %}
                     <option value="{{ theme }}">{{ theme }}</option>
                     {% endfor %}
                    </select>
                    <button type="submit">Commencer</button>
                </form>
            </div>
    </div>
{% endblock %}

app/templates/quiz.html
{% extends "base.html" %}

{% block title %}Quiz - QCM{% endblock %}

{% block content %}

<div class="container fade-in">
    <h2>Thème : {{ theme }}</h2>
    <form 
        {% if user_answer is not none %}
            method="GET"
            action="{% if question_index + 1 < questions|length %}
                        {{ url_for('main.quiz', theme=theme, question_index=question_index + 1) }}
                    {% else %}
                        {{ url_for('main.result', theme=theme) }}
                    {% endif %}"
        {% else %}
            method="POST"
            action="{{ url_for('main.quiz', theme=theme, question_index=question_index) }}"
        {% endif %}
    >
        <div class="quiz-question">
            <div class="quiz-numero"></div>
            <div class="quiz-text">
                <p class="score">Score : {{ score }}</p>
                <p class="quiz-intitule">Question {{ question_index + 1 }} sur {{ total_questions }} : {{ question['question'] }}</p>
                <div class="quiz-choices">
                    <ul>
                        {% if question['type'] == 'radio' %}
                            {% for option in question['options'] %}
                                <li {% if user_answer is not none %}
                                        {% if option == question['correct'] %}
                                            style="color: white;background-color: rgb(98, 150, 93); font-weight:bolder;"
                                        {% elif user_answer[0] == option and option != question['correct'] %}
                                            style="color: red;"
                                        {% endif %}
                                    {% endif %}>
                                    <input type="radio" 
                                           id="q{{ question_index }}_{{ loop.index0 }}" 
                                           name="answer" 
                                           value="{{ option }}" 
                                           {% if user_answer and option == user_answer[0] %} checked {% endif %}>
                                    <label for="q{{ question_index }}_{{ loop.index0 }}"
                                           >
                                        {{ option }}
                                    </label>
                                </li>
                            {% endfor %}
                        {% elif question['type'] == 'checkbox' %}
                            {% for option in question['options'] %}
                                <li {% if user_answer is not none %}
                                        {% if option == question['correct'] %}
                                            style="color: white;background-color: rgb(98, 150, 93); font-weight:bolder;"
                                        {% elif user_answer[0] == option and option != question['correct'] %}
                                            style="color: red;"
                                        {% endif %}
                                    {% endif %}>
                                    <input type="checkbox" 
                                           id="q{{ question_index }}_{{ loop.index0 }}" 
                                           name="answer" 
                                           value="{{ option }}" 
                                           {% if user_answer and option in user_answer %} checked {% endif %}>
                                    <label for="q{{ question_index }}_{{ loop.index0 }}">
                                        {{ option }}
                                    </label>
                                </li>
                            {% endfor %}                        
                        {% elif question['type'] == 'text' %}
                            <li>
                                <label for="q{{ question_index }}_text">Votre réponse :</label>
                                <input type="text" 
                                    id="q{{ question_index }}_text" 
                                    name="answer" 
                                    value="{{ user_answer if user_answer else '' }}"
                                    autocomplete="off">
                            </li>
                        {% endif %}
                    </ul>
                </div>
                
            </div>
        </div>
        <button type="submit">
            {% if user_answer is not none %}
                {% if question_index + 1 < questions|length %}
                    Question suivante
                {% else %}
                    Voir les résultats
                {% endif %}
            {% else %}
                Soumettre
            {% endif %}
        </button>
    </form>

    {% if user_answer is not none %}
        <p>
            {% if is_correct %}
                <span style="color: green;justify-content: center;margin: auto;">🎉 Bonne réponse ! {{ question['correct'] }}</span>
            {% else %}
                <span style="color: red;">❌ Mauvaise réponse. La bonne réponse était : {{ question['correct'] }}</span>
            {% endif %}
                <br>
                <span style="font-style: italic;">Exemple : </span>                
                <span style="background-color: black;color: aliceblue; font-family: 'Courier New', Courier, monospace; padding: .8em;"> {{ question['example'] }} </span>
                <span>Explication : {{ question['explication'] }}</span>
        </p>
    {% endif %}
</div>

{% endblock %}

<script>
document.addEventListener('DOMContentLoaded', function() {
    const form = document.querySelector('form');
    if (form) {
        form.addEventListener('submit', function() {
            const textInput = document.querySelector('input[type="text"][name="answer"]');
            if (textInput) {
                setTimeout(() => { textInput.value = ''; }, 10);
            }
        });
    }
});
</script>

app/templates/result.html
{% extends "base.html" %}

{% block title %}Résultats - QCM{% endblock %}

{% block content %}
    <div class="container fade-in">
        <h1>Résultats</h1>
        <p>Votre score est : {{ score }} / {{ total_questions }} <strong>soit {{ success_rate }} %</strong></p>

        <h2>Réponses Incorrectes</h2>
        <ol>
            {% if wrong_answers %}
                {% for wrong in wrong_answers %}
                    <li>
                        <strong>{{ wrong['question'] }}</strong><br/>
                        <!-- Votre réponse : <span style="color: rgb(173, 17, 17);">{{ wrong['user_answer'] if wrong['user_answer'] is not none else '' }}
</span><br/> -->
                        Votre réponse : <span style="color: rgb(173, 17, 17);">𐄂 {{ wrong['user_answer'] }}</span><br/>

                        Bonne réponse : <span style="color: darkgreen;"><strong>✔ {{ wrong['correct_answer'] }}</strong></span>
                    </li>
                    <br/>
                {% endfor %}
            {% else %}
                <p>Aucune réponse incorrecte, bravo !</p>
            {% endif %}
        </ol>

        <h2>Réponses Correctes :</h2>
        <ol>
            {% for answer in correct_answers %}
                <li>{{ answer['question'] }} :<br/>
                    <B style="color: darkgreen;">✔ {{ answer['correct_answer'] }}</B></li>
                <br/>
            {% endfor %}
        </ol>
        <a href="{{ url_for('main.index') }}">Retour au menu principal</a>
    </div>

{% endblock %}